server:
 port: 9191

spring:
 application:
  name: API-GATEWAY
 cloud:
  gateway:
   routes:
    - id: USER-SERVICE
      uri: lb://USER-SERVICE
      predicates:
       - Path=/users/**
    - id: DEPARTMENT-SERVICE
      uri: lb://DEPARTMENT-SERVICE
      predicates:
       - Path=/departments/**
  management:
   endpoints:
    web:
     exposure:
      include: "*"
      exclude: " env, beans"
    info:
     enabled: true