server:
 port: 9001

logging:
 level:
  root: INFO

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/javafsd
    username: root
    password: root
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
  application:
   name: DEPARTMENT-SERVICE
  zipkin:
   base-url: http://localhost:9411/
  